name: React-App Deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Push and deploy
        run: cd /var/www/html && git pull origin master && npm run build
